# Site Settings
title: Arpit Jindal
url: 'https://jindalarpit.github.io/resume/'
baseurl: '/resume'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6

#Profile information
name: Arpit Jindal
tagline: Project Lead
pic: profile.jpg
summary: |
  - 11 years of rich experience working with Java/J2EE and Spring framework.
  - Involved in Requirement Management, Solution Design, Risk Management and Implementation phases.
  - Exposure to microservices architecture using Spring boot and Kotlin.
  - Worked on cloud infrastructure automation using Infrastructure as code using Terraform, packer, chef etc.
  - Good handson and working experience setting up **Kubernetes cluster** and deep knowledge managing highly distributed microservices architecture using Istio.
  - Working experience on different AWS services like EKS, MSK, EC2, ASG, Subnets etc.
  - Understanding of Event driven architecture.
  - Execution of Performance and security testing for microservices.
  - Suggested Security improvements and cost optimization for cloud platform.

#sidebar links
email: jindalarpit@gmail.com
email-displayname: jindlarpit
phone: +91 9958198335
linkedin: jindalarpit
linkedin-displayname: Arpit Jindal
github: jindalarpit
twitter: '@jindalarpit'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics:

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
