# Site Settings
title: Arpit Jindal
url: 'https://jindalarpit.github.io/resume/'
baseurl: '/resume'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6

#Profile information
name: Arpit Jindal
tagline: Project Lead
pic: profile.jpg
summary: |
  - **11 years** of rich experience development of application using Java/J2EE and Spring framework.
  - Experience in Microservices Architecture design and development with AWS cloud, kubernetes, Istio and docker containers.
  - Expertise in devops and agile methodology.
  - Strong Technical and problem solving skills coupled with decision making capabilities for enabling effective solutions, leading to high customer satisfaction.
  - Proficiency in Requirement Management, Solution Design, Risk Management, code reviews, and Implementation.
  - Strong communication and interpersonal skills backed by sound analytical, technical and leadership skills.
  - Exposure to **microservices architecture using Spring boot** and Kotlin.
  - Expertise on cloud infrastructure automation using **Infrastructure as a code** with Terraform, packer, chef etc.
  - Good hands-on experience setting up **Kubernetes cluster** and **Istio Service Mesh**.
  - Working experience on different **AWS services** like EKS, MSK, EC2, ASG, Subnets etc.
  - Good understanding of **Event driven architecture using Kafka**.
  - Execution of Performance and security testing for microservices.
  - Involved in Security improvements and cost optimization for cloud platform.

#sidebar links
email: jindalarpit@gmail.com
email-displayname: jindlarpit
phone: +91 9958198335
linkedin: jindalarpit
linkedin-displayname: Arpit Jindal
github: jindalarpit
twitter: '@jindalarpit'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics:

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
